spring.application.name=carsales
spring.datasource.url=jdbc:postgresql://localhost:5432/CarSales
spring.datasource.username=postgres
spring.datasource.password=[DB password]

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3